version: '3'
services:
  minio:
    container_name: minio_server
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'remosto'
      MINIO_ROOT_PASSWORD: 'remosto123'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086" 
    volumes:
      - influxdb-storage:/var/lib/influxdb

  sparka-api:
    image: docker.io/equehours/sparka-api:latest
    container_name: sparka-api
    ports:
      - "5000:5000"
      - "5001:5001"

volumes:
  minio_data:
  grafana-storage:
  influxdb-storage: