version: "3"

services:
  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://remosto:remosto123@postgres_server:5432/lakefs?sslmode=disable
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=remosto
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=remosto123
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_STATS_ENABLED
      - LAKEFS_LOGGING_LEVEL
      - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=remosto
      - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=remosto123
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
    entrypoint: ["/bin/sh", "-c"]
    command:
        - |
          lakefs setup --local-settings --user-name docker --access-key-id remosto --secret-access-key remosto123 || true
          lakefs run --local-settings

  # minio-setup:
  #   image: minio/mc
  #   container_name: minio-setup
  #   environment:
  #       - MC_HOST_lakefs=http://remosto:remosto123@minio:9000
  #   depends_on:
  #     - minio
  #   command: ["mb", "lakefs/example"]

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'remosto'
      MINIO_ROOT_PASSWORD: 'remosto123'
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]

  postgres:
    image: postgres:13
    container_name: postgres_server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=remosto
      - POSTGRES_PASSWORD=remosto123
      - POSTGRES_DB=lakefs

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SERVER_NAME=PostgreSQL
      - PGADMIN_SERVER_PORT=5432
      - PGADMIN_SERVER_HOST=postgres_server
      - PGADMIN_SERVER_USER=remosto
      - PGADMIN_SERVER_PASSWORD=remosto123
    ports:
      - "8081:80"
    depends_on:
      - postgres