version: '3'
services:
  minio:
    container_name: minio_server
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'remosto'
      MINIO_ROOT_PASSWORD: 'remosto123'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  minio-gateway: 
    container_name: minio_gateway
    image: minio-gateway:latest
    ports:
      - 5002:5002
    depends_on:
      - minio

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"  
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  

  influxdb-gateway:
    image: influxdb-gateway:latest
    container_name: influxdb_gateway
    ports:
      - "5000:5000"  

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086" 
    volumes:
      - influxdb-storage:/var/lib/influxdb2

  sparka-api:
    image: sparka-api:latest
    container_name: sparka_api
    depends_on:
      - influxdb
      - influxdb-gateway
      - minio
    ports:
      - "5001:5001"

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sparka-api

volumes:
  minio_data:
  grafana-storage:
  influxdb-storage: