global:
  scrape_interval: 15s 
  evaluation_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: ["localhost:9091"]

  - job_name: docker

    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: node
    static_configs:
    - targets:
       - node-exporter:9101
