# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"K\n\x05Plate\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"1\n\rPlateResponse\x12 \n\x06plates\x18\x01 \x03(\x0b\x32\x10.detection.Plate2O\n\x0ePlateDetection\x12=\n\x06\x44\x65tect\x12\x17.detection.ImageRequest\x1a\x18.detection.PlateResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREQUEST._serialized_start=30
  _IMAGEREQUEST._serialized_end=64
  _PLATE._serialized_start=66
  _PLATE._serialized_end=141
  _PLATERESPONSE._serialized_start=143
  _PLATERESPONSE._serialized_end=192
  _PLATEDETECTION._serialized_start=194
  _PLATEDETECTION._serialized_end=273
# @@protoc_insertion_point(module_scope)
