# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vehicle_detection_pb2 as vehicle__detection__pb2


class VehicleDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/vehicle_detection.VehicleDetection/Detect',
                request_serializer=vehicle__detection__pb2.ImageRequest.SerializeToString,
                response_deserializer=vehicle__detection__pb2.VehicleResponse.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/vehicle_detection.VehicleDetection/UpdateModel',
                request_serializer=vehicle__detection__pb2.ModelRequest.SerializeToString,
                response_deserializer=vehicle__detection__pb2.ModelResponse.FromString,
                )


class VehicleDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=vehicle__detection__pb2.ImageRequest.FromString,
                    response_serializer=vehicle__detection__pb2.VehicleResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=vehicle__detection__pb2.ModelRequest.FromString,
                    response_serializer=vehicle__detection__pb2.ModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_detection.VehicleDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VehicleDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicle_detection.VehicleDetection/Detect',
            vehicle__detection__pb2.ImageRequest.SerializeToString,
            vehicle__detection__pb2.VehicleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicle_detection.VehicleDetection/UpdateModel',
            vehicle__detection__pb2.ModelRequest.SerializeToString,
            vehicle__detection__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
