# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehicle_detection.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vehicle_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17vehicle_detection.proto\x12\x11vehicle_detection\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"e\n\x07Vehicle\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x16\n\x0e\x64\x65tected_class\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"?\n\x0fVehicleResponse\x12,\n\x08vehicles\x18\x01 \x03(\x0b\x32\x1a.vehicle_detection.Vehicle\"!\n\x0cModelRequest\x12\x11\n\tmodel_url\x18\x01 \x01(\t\"1\n\rModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb7\x01\n\x10VehicleDetection\x12O\n\x06\x44\x65tect\x12\x1f.vehicle_detection.ImageRequest\x1a\".vehicle_detection.VehicleResponse\"\x00\x12R\n\x0bUpdateModel\x12\x1f.vehicle_detection.ModelRequest\x1a .vehicle_detection.ModelResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=46
  _globals['_IMAGEREQUEST']._serialized_end=80
  _globals['_VEHICLE']._serialized_start=82
  _globals['_VEHICLE']._serialized_end=183
  _globals['_VEHICLERESPONSE']._serialized_start=185
  _globals['_VEHICLERESPONSE']._serialized_end=248
  _globals['_MODELREQUEST']._serialized_start=250
  _globals['_MODELREQUEST']._serialized_end=283
  _globals['_MODELRESPONSE']._serialized_start=285
  _globals['_MODELRESPONSE']._serialized_end=334
  _globals['_VEHICLEDETECTION']._serialized_start=337
  _globals['_VEHICLEDETECTION']._serialized_end=520
# @@protoc_insertion_point(module_scope)
