# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plate_text_extraction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bplate_text_extraction.proto\x12\x15plate_text_extraction\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2l\n\x13PlateTextExtraction\x12U\n\x07\x45xtract\x12#.plate_text_extraction.ImageRequest\x1a#.plate_text_extraction.TextResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plate_text_extraction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREQUEST._serialized_start=54
  _IMAGEREQUEST._serialized_end=88
  _TEXTRESPONSE._serialized_start=90
  _TEXTRESPONSE._serialized_end=118
  _PLATETEXTEXTRACTION._serialized_start=120
  _PLATETEXTEXTRACTION._serialized_end=228
# @@protoc_insertion_point(module_scope)
